# Generated by Django 4.1.1 on 2022-09-17 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SampleAttributeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attr1', models.CharField(db_index=True, max_length=50)),
                ('attr2', models.CharField(db_index=True, max_length=50)),
                ('attr3', models.CharField(db_index=True, max_length=50)),
                ('attr4', models.CharField(db_index=True, max_length=50)),
                ('attr5', models.CharField(db_index=True, max_length=50)),
                ('sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='api.samplemodel')),
            ],
            options={
                'db_table': 'sample_attribute_tbl',
            },
        ),
    ]
