# Generated by Django 4.1 on 2022-09-04 07:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_userinfomodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAttributeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attr1', models.CharField(db_index=True, max_length=50)),
                ('attr2', models.CharField(db_index=True, max_length=50)),
                ('attr3', models.CharField(db_index=True, max_length=50)),
                ('attr4', models.CharField(db_index=True, max_length=50)),
                ('attr5', models.CharField(db_index=True, max_length=50)),
                ('user_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.userinfomodel')),
            ],
            options={
                'db_table': 'user_attribute_tbl',
            },
        ),
    ]
