# Generated by Django 4.1.1 on 2022-09-12 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_userattributemodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userattributemodel',
            name='user_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='api.userinfomodel'),
        ),
    ]
