import React, {useState, useEffect} from 'react'

import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'

import { AuthUseCase } from "../usecase/auth";


const Home: NextPage = () => {
    const [email, setEmail] = useState('')
    const [password, setPassword] = useState('')
    const [token, setToken] = useState({})

    useEffect(() => {
      console.log('use effect')
      console.log(token)
    }, [token])

    const Login = async (email: string, password: string) => {
        const auth_usecase = new AuthUseCase()
        const result = await auth_usecase.login(email, password)
        setToken(result)
        console.log('click!!')
    }

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.4/css/bulma.min.css" />
      </Head>

      <div className="field">
        <p className="control has-icons-left has-icons-right">
          <input id="email" className="input" type="email" placeholder="Email" onChange={(e) => setEmail(e.target.value)} />
          <span className="icon is-small is-left">
            <i className="fas fa-envelope"></i>
          </span>
          <span className="icon is-small is-right">
            <i className="fas fa-check"></i>
          </span>
        </p>
      </div>
      <div className="field">
        <p className="control has-icons-left">
          <input id="password" className="input" type="password" placeholder="Password" onChange={(e) => setPassword(e.target.value)} />
          <span className="icon is-small is-left">
            <i className="fas fa-lock"></i>
          </span>
        </p>
      </div>
      <div className="field">
        <p className="control">
          <button className="button is-success" onClick={ async (e) => {
              await Login(email, password)
            }
          }>
            Login
          </button>
        </p>
      </div>

    </div>




  )
}

export default Home
